# Generated by Django 4.2.10 on 2025-02-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='wire_aba_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='wire_ach_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
