# Generated by Django 4.2.10 on 2025-02-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_company_wire_aba_number_company_wire_ach_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ifsc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
