# Generated by Django 4.2.10 on 2025-01-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financerequest_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerequest',
            name='advanced_billing_raised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='client_rejected_sample',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='final_sample_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Advanced Invoice', 'Advanced Invoice'), ('Completed Invoice', 'Completed Invoice'), ('Invoice to be Raised', 'Invoice to be Raised'), ('Open Invoice', 'Open Invoice'), ('Close Invoice', 'Close Invoice'), ('Project Close', 'Project Close'), ('Advanced Billing Raised', 'Advanced Billing Raised')], default='Pending', max_length=50),
        ),
    ]
