# Generated by Django 4.2.10 on 2025-01-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_alter_project_status'),
        ('user', '0002_department_company'),
        ('finance', '0006_financerequest_advanced_billing_raised_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceBillingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('advanced_billing', models.CharField(blank=True, max_length=150, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userrole')),
            ],
        ),
    ]
