# Generated by Django 4.2.10 on 2025-01-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_advancebillingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financerequest',
            name='final_sample_size',
        ),
    ]
