# Generated by Django 4.2.10 on 2025-01-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_financerequest_final_sample_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerequest',
            name='final_samples',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
