# Generated by Django 4.2.10 on 2025-01-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_department_company'),
        ('project', '0044_project_advance_billing_raised'),
        ('finance', '0009_financerequest_final_samples'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('data', models.JSONField(blank=True, null=True)),
                ('name_of_client', models.CharField(blank=True, max_length=255, null=True)),
                ('project_code', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_services', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('name_of_project_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vpr_approved', to='user.userrole')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vpr_created', to='user.userrole')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vpr_projects', to='project.project')),
            ],
        ),
    ]
