# Generated by Django 4.2.10 on 2025-01-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_vpr'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerequest',
            name='advance_billing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='financerequest',
            name='status',
            field=models.CharField(choices=[('Invoice to be Raised', 'Invoice to be Raised'), ('Invoice Generated', 'Invoice Generated'), ('Payment Received', 'Payment Received'), ('Advanced Billing Raised', 'Advanced Billing Raised'), ('Advanced Invoice Generated', 'Advanced Invoice Generated'), ('Advance Payment Received', 'Advance Payment Received')], default='Invoice to be Raised', max_length=50),
        ),
    ]
