# Generated by Django 4.2.10 on 2025-01-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_notification_notification_type'),
        ('user', '0002_department_company'),
        ('finance', '0011_financerequest_advance_billing_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerequest',
            name='cbr_raised_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbr_finance_requests', to='user.userrole'),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='cbr_raised_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.client'),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='client_cc_emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='client_contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='client_email_address',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='client_purchase_order_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='number_of_additional_surveys',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='number_of_surveys_initial_sow',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='other_billing_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='project_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='project_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='sales_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='total_surveys_to_be_billed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AdvanceBillingRequest',
        ),
    ]
