# Generated by Django 4.2.10 on 2025-01-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_department_company'),
        ('finance', '0012_financerequest_cbr_raised_by_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('buyer_name', models.CharField(max_length=255)),
                ('services', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost_components', models.JSONField()),
                ('total_cost_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_terms', models.TextField(default='Payment to be released within 30 days from the date of invoice.')),
                ('account_title', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('swift_code', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_address', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
            ],
        ),
    ]
