# Generated by Django 4.2.10 on 2025-01-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='account_title',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bank_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='swift_code',
        ),
    ]
