# Generated by Django 4.2.10 on 2025-01-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_invoice_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financerequest',
            name='client',
        ),
    ]
