# Generated by Django 4.2.10 on 2025-01-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_remove_financerequest_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerequest',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
