# Generated by Django 4.2.10 on 2025-01-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_financerequest_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerequest',
            name='cbr_raised_status',
            field=models.BooleanField(default=False),
        ),
    ]
