# Generated by Django 4.2.10 on 2025-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_financerequest_cbr_raised_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerequest',
            name='client_rejected_sample',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
