# Generated by Django 4.2.10 on 2025-01-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_financerequest_client_rejected_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerequest',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
