# Generated by Django 4.2.10 on 2025-02-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_advancebillingrequisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancebillingrequisition',
            name='client_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advancebillingrequisition',
            name='client_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
