# Generated by Django 4.2.10 on 2025-02-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_notification_notification_type'),
        ('user', '0005_company_logo'),
        ('finance', '0022_advancebillingrequisition_client_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financerequest',
            name='project_manager_name',
        ),
        migrations.AddField(
            model_name='financerequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.client'),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager_cbr', to='user.userrole'),
        ),
        migrations.AlterField(
            model_name='financerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userrole'),
        ),
        migrations.AlterField(
            model_name='financerequest',
            name='status',
            field=models.CharField(choices=[('Invoice to be Raised', 'Invoice to be Raised'), ('Invoice Generated', 'Invoice Generated'), ('Payment Received', 'Payment Received'), ('Advanced Billing Raised', 'Advanced Billing Raised'), ('Advanced Invoice Generated', 'Advanced Invoice Generated'), ('Advance Payment Received', 'Advance Payment Received'), ('CBR Raised', 'CBR Raised')], default='Invoice to be Raised', max_length=50),
        ),
    ]
