# Generated by Django 4.2.10 on 2025-02-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_remove_financerequest_project_manager_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financerequest',
            old_name='other_billing_instructions',
            new_name='other_billing_instruction',
        ),
    ]
