# Generated by Django 4.2.10 on 2025-02-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_rename_other_billing_instructions_financerequest_other_billing_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerequest',
            name='number_of_additional_surveys',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
