# Generated by Django 4.2.10 on 2025-02-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_company_logo'),
        ('project', '0045_notification_notification_type'),
        ('finance', '0025_alter_financerequest_number_of_additional_surveys'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='abr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abrinvoices', to='finance.advancebillingrequisition'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cbr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbrinvoices', to='finance.financerequest'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_created_by', to='user.userrole'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='iban_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ifsc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='project.project'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sort_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Invoice to be Raised', 'Invoice to be Raised'), ('Invoice Generated', 'Invoice Generated'), ('Partially Paid', 'Partially Paid'), ('Payment Received', 'Payment Received'), ('Advanced Billing Raised', 'Advanced Billing Raised'), ('Advanced Invoice Generated', 'Advanced Invoice Generated'), ('Advance Payment Received', 'Advance Payment Received')], default='Invoice to be Raised', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='swift_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('CBR', 'Client Billing Request'), ('ABR', 'Advance Billing Requisition')], default='CBR', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wire_aba_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wire_ach_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
