# Generated by Django 4.2.10 on 2025-03-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_invoicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancebillingrequisition',
            name='clientname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
