# Generated by Django 4.2.10 on 2025-01-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_alter_projectupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='trck_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
