# Generated by Django 4.2.10 on 2024-09-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_projectupdateddata_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_client_pm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_unimrkt_pm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
