# Generated by Django 4.2.10 on 2024-09-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_project_project_client_pm_project_project_unimrkt_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='purchase_order_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
