# Generated by Django 4.2.10 on 2024-10-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_alter_client_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(blank=True, max_length=50, null=True)),
                ('cpi', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_samples', to='project.project')),
            ],
        ),
    ]
