# Generated by Django 4.2.10 on 2024-10-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_projectsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsample',
            name='target_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
