# Generated by Django 4.2.10 on 2024-10-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_projectsample_target_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_multiple_sample_cpi',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
