# Generated by Django 4.2.10 on 2024-10-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_project_is_multiple_sample_cpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsample',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_samples', to='project.project'),
        ),
    ]
