# Generated by Django 4.2.10 on 2024-11-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
