# Generated by Django 4.2.10 on 2024-11-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_projectdocument_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsample',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsample',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
