# Generated by Django 4.2.10 on 2024-12-06 11:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_department_company'),
        ('project', '0035_projectsample_date_projectsample_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsample',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectsample',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectsample',
            name='pending_changes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsample',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 6, 11, 51, 45, 136851, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsample',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userrole'),
        ),
    ]
