# Generated by Django 4.2.10 on 2024-12-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_alter_notification_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
