# Generated by Django 4.2.10 on 2024-12-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_notification_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='label_cost',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
