# Generated by Django 4.2.10 on 2025-01-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_project_label_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsample',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
