# Generated by Django 4.2.10 on 2025-01-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_alter_projectsample_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Project Initiated', 'Project Initiated'), ('To Be Started', 'To Be Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('CBR Raised', 'CBR Raised')], default='Project Initiated', max_length=20),
        ),
    ]
