# Generated by Django 4.2.10 on 2025-01-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='advance_billing_raised',
            field=models.BooleanField(default=False),
        ),
    ]
