# Generated by Django 4.2.10 on 2025-01-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_project_advance_billing_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('VPR', 'VPR'), ('CBR', 'CBR')], max_length=20, null=True),
        ),
    ]
