# Generated by Django 4.2.10 on 2025-03-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
