# Generated by Django 4.2.10 on 2025-03-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_client_pin_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
